export const TYPOGRAPHY = {
  "fontFamilies": {
    "inter": "Inter",
    "ibm-plex-mono": "IBM Plex Mono"
  },
  "lineHeights": {
    "0": "1.1rem",
    "1": "1.3rem",
    "2": "1.5rem",
    "3": "1.8rem",
    "4": "1.9rem",
    "5": "2.0rem",
    "6": "2.4rem",
    "7": "2.8rem",
    "8": "3.8rem",
    "9": "4.5rem",
    "10": "5.6rem"
  },
  "fontWeights": {
    "400": 400,
    "500": 500,
    "600": 600,
    "700": 700,
    "code-700": 700,
    "code-600": 600,
    "code-500": 500,
    "code-400": 400
  },
  "fontSize": {
    "0": "0.8rem",
    "1": "0.9rem",
    "2": "1.0rem",
    "3": "1.1rem",
    "4": "1.3rem",
    "5": "1.5rem",
    "6": "1.9rem",
    "7": "2.3rem",
    "8": "3.0rem",
    "9": "3.8rem",
    "10": "4.5rem"
  },
  "letterSpacing": {
    "0": "0%",
    "1": "-2%"
  },
  "paragraphIndent": {
    "0": "0.8rem"
  },
  "paragraphSpacing": {
    "0": "0.8rem",
    "1": "0.9rem",
    "2": "1.0rem",
    "3": "1.1rem",
    "4": "1.3rem",
    "5": "1.5rem",
    "6": "1.9rem",
    "7": "2.3rem",
    "8": "3.0rem",
    "9": "3.8rem",
    "10": "4.5rem"
  },
  "textCase": {
    "none": "none"
  },
  "textDecoration": {
    "none": "none"
  },
  "textStyles": {
    "main-xs-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xs-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xs-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xs-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-sm-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-sm-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-sm-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-sm-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-md-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-md-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-md-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-md-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-lg-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-lg-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-lg-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-lg-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-2xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-2xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-2xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-2xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-3xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-3xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-3xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-3xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-4xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-4xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-4xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-4xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-5xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "3.8rem",
      "fontSize": "3.0rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-5xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "3.8rem",
      "fontSize": "3.0rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-5xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "3.8rem",
      "fontSize": "3.0rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-5xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "3.8rem",
      "fontSize": "3.0rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-6xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "4.5rem",
      "fontSize": "3.8rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-6xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "4.5rem",
      "fontSize": "3.8rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-6xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "4.5rem",
      "fontSize": "3.8rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-6xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "4.5rem",
      "fontSize": "3.8rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "3.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-7xl-bold": {
      "fontFamily": "Inter",
      "fontWeight": 700,
      "lineHeight": "5.6rem",
      "fontSize": "4.5rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "4.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-7xl-semibold": {
      "fontFamily": "Inter",
      "fontWeight": 600,
      "lineHeight": "5.6rem",
      "fontSize": "4.5rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "4.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-7xl-medium": {
      "fontFamily": "Inter",
      "fontWeight": 500,
      "lineHeight": "5.6rem",
      "fontSize": "4.5rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "4.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "main-7xl-regular": {
      "fontFamily": "Inter",
      "fontWeight": 400,
      "lineHeight": "5.6rem",
      "fontSize": "4.5rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "4.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xs-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xs-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xs-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xs-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "1.1rem",
      "fontSize": "0.8rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.8rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-sm-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-sm-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-sm-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-sm-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "1.3rem",
      "fontSize": "0.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "0.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-md-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-md-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-md-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-md-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "1.5rem",
      "fontSize": "1.0rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.0rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-lg-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-lg-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-lg-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-lg-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "1.8rem",
      "fontSize": "1.1rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.1rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xl-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xl-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xl-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-xl-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "1.9rem",
      "fontSize": "1.3rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-2xl-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-2xl-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-2xl-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-2xl-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "2.0rem",
      "fontSize": "1.5rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.5rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-3xl-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-3xl-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-3xl-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-3xl-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "2.4rem",
      "fontSize": "1.9rem",
      "letterSpacing": "0%",
      "paragraphSpacing": "1.9rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-4xl-bold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 700,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-4xl-semibold": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 600,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-4xl-medium": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 500,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    },
    "code-4xl-regular": {
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "lineHeight": "2.8rem",
      "fontSize": "2.3rem",
      "letterSpacing": "-2%",
      "paragraphSpacing": "2.3rem",
      "paragraphIndent": "0.8rem",
      "textCase": "none",
      "textDecoration": "none"
    }
  }
};