export enum AssetSortAdoType {
    AddressList,
    // Ado,
    App,
    Auction,
    CW20,
    CW20Exchange,
    // CW20Staking,
    CW721,
    // CW721Bids,
    // CW721Timelock,
    Crowdfund,
    // Factory,
    // Gumball,
    // Lockdrop,
    Marketplace,
    // MerkleAirdrop,
    // NftStaking,
    Primitive,
    // RateLimitingWithdrawals,
    Rates,
    // Receipt,
    Splitter,
    // Timelock,
    // Unknown,
    Vault,
    // Vesting,
    // WeightedDistributionSplitter,
    // WeightedSplitter,
    // WrappedCW721
}